trigger:
  branches:
    include:
      - main

variables:
  imageName: test-postgres
  acrName: mydockerlearnacr
  acrLoginServer: mydockerlearnacr.azurecr.io

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: Dockerfile
    tags: |
      latest
      $(Build.BuildId)
    azureSubscription: acr-service-connection
    azureContainerRegistry: $(acrLoginServer)
